# Generated by Django 3.2.4 on 2021-09-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pelajaran', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pelajaran', models.CharField(blank=True, max_length=200, null=True)),
                ('file_pelajaran', models.FileField(upload_to='materi/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
