# Generated by Django 3.2.4 on 2021-09-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matakul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_matkul', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_matkul', models.CharField(blank=True, max_length=200, null=True)),
                ('mapel', models.ManyToManyField(to='myapi.Mapel')),
            ],
        ),
    ]
