# Generated by Django 3.2.4 on 2021-09-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_matakul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='file_pelajaran',
        ),
        migrations.CreateModel(
            name='Arsip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
                ('file_pelajaran', models.FileField(upload_to='materi/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.mapel')),
            ],
        ),
    ]
