# Generated by Django 3.2.4 on 2021-09-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0006_auto_20210909_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absensi',
            name='user',
        ),
        migrations.AddField(
            model_name='absensi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
